In [2]:
import numpy as np

def array_ones(shape):
    return np.ones(shape)

print(array_ones([2,3,4]))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
def identity_matrix1(n,m):
    return n*np.eye(m)

print(identity_matrix1(5,5))

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [4]:
#Write a numpy funtions that takes 3 numbers- a start, stop and a n samples

def linspaceproblem(start,stop,n):
    return np.linspace(start,stop,n)
print(linspaceproblem(0,50,6))

[ 0. 10. 20. 30. 40. 50.]


In [5]:
# Write a function that takes a list of numbers and returns a square NumPy matrix with the given numbers on the diagonal.

def diagmatrix(lst):
    return np.diag(lst)
print(diagmatrix([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [6]:
#Write a function that takes a 2-dimensional NumPy array and returns a new array with the diagonal elements of the original array.

def extract_diagonal(arr):
    return np.diag(arr)
print(extract_diagonal([[10, 20, 30],[40, 50, 60],[70, 80, 90]]))

[10 50 90]


In [7]:
#Write a function that takes a list of integers shape and a fill value val and returns a NumPy array with the given shape filled with the given fill value.

def custom_filled_array(shape,val):
    return np.full(shape,val)
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [8]:
# Write a function that takes two NumPy arrays and returns a NumPy array with the common elements of the two arrays.

def common_elements(arr1,arr2):
    return np.intersect1d(arr1,arr2)

# Example
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print(common_elements(a, b))

[3 4]


In [9]:
# Write a function that takes an integer n and returns a NumPy array with the lower triangle of a matrix of size (n, n)filled with ones and the rest of the elements filled with zeros.

def lower_triangle_ones(n):
    return np.tril(np.ones((n,n)))
print(lower_triangle_ones(3))

#Udemy code

def lower_triangle_ones_2(n):
    return np.tri(n)
print(lower_triangle_ones_2(4))

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [10]:
#Write a function that takes an integer n and returns a NumPy array with the upper triangle of a matrix of size (n, n)filled with ones and the rest of the elements filled with zeros.

def upper_triangle_ones(n):
    return np.triu(np.ones((n,n)))
print(upper_triangle_ones(3))


[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [11]:
#Given a 1D NumPy array arr, use the reshape function to create a 2D NumPy array with 2 rows and 4 columns, such that the elements of arr are arranged in the resulting array in row-major order.
def array_reshape(a,b):
    arr = np.arange(12, dtype='int')
    return arr.reshape(a,b)
print(array_reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# Given a 2D NumPy array arr, use the reshape function to flatten the array into a 1D NumPy array.
def array_flatten():
    a = np.arange(12, dtype='int').reshape(3, 4)
    return np.reshape(a,12,order='F')
print(array_flatten())

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [13]:
#Given a 2D NumPy array of shape (3,4), add a new axis to the array in such a way that the resulting array has shape (1,3,4).

def add_axis():
    a = np.arange(12, dtype='int').reshape(3, 4)
    return a.reshape(1,3,4)
b=add_axis()
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [14]:
# Given a 2D NumPy array a, use the ravel function to flatten the array into a 1D NumPy array, and then use slicing to reverse the flattened array.

def flatten_and_reverse():
    a=np.arange(12).reshape(3,4)
    #Flatten the array using ravel()
    flattened=a.ravel()
    #Reverse the flattened array
    reversed_arr=flattened[::-1]
    return reversed_arr
print(flatten_and_reverse())

[11 10  9  8  7  6  5  4  3  2  1  0]


In [15]:
#Given a 2D numpy array and a value, set all the negative elements of the array to the given value and print the array arr.

arr = np.array([[-1, 2, -3], [4, -5, 6]])
value = 0
print(arr)
np.copyto(arr,value,where=arr<0)
print(arr)

[[-1  2 -3]
 [ 4 -5  6]]
[[0 2 0]
 [4 0 6]]


In [16]:
#Given two 1D numpy arrays of the same length and a value, set all the elements of the first array to the given value if the corresponding element in the second array is negative.

arr1 = np.array([1, 2, 9, 4, 10])
arr2 = np.array([-1, -2, 3, -4, 5])

value = 0
print(arr1)
print(arr2)
print('----------')
print('SOLUTION BELOW')
print('----------')
np.copyto(arr1,value,where=arr2<0)
print(arr1)

[ 1  2  9  4 10]
[-1 -2  3 -4  5]
----------
SOLUTION BELOW
----------
[ 0  0  9  0 10]


In [17]:
#Write a function, which returns True if the array is a 2D square matrix (i.e., has the same number of rows and columns), and False otherwise. 

def is_square_matrix(arr):
    rows,cols=np.shape(arr)
    return rows==cols

# Example test cases
sample_array1 = np.array([[1, 2], [3, 4]])
sample_array2 = np.array([[1, 2, 3], [4, 5, 6]])

print(is_square_matrix(sample_array1))

True


In [18]:
#Write a function that takes a numpy array as input and returns a new 1D array with the elements of the input array in reverse order. 
# Use the numpy.ndarray.flatten method to flatten the input array, and then use slicing to reverse the flattened array.

def reverse_array(arr):
    a=arr.flatten()
    a=a[::-1]
    return a

# Example
a = np.array([[1, 2, 3],[4, 5, 6]])

print(reverse_array(a))



[6 5 4 3 2 1]


In [19]:
# Write a function that takes a numpy array as input and returns the sum of the elements of the array. 
# Use the numpy.ndarray.flatten method to flatten the input array, and then use the sum function to compute the sum of the elements.

def sum_array(arr):
    a=arr.flatten()
    return a.sum()

#Example
a = np.array([[1, 2],[3, 4]])

print(sum_array(a))

10


In [20]:
# Write a function that takes a 2D numpy array and returns a new array with the rows and columns of the input array swapped. 
# For example array [[1, 2, 3], [4, 5, 6] is transposed as [[1, 4], [2, 5], [3, 6]]

def transpose_array(arr):
    transpose_arr=np.transpose(arr)
    return transpose_arr

#Example

a = np.array([[1, 2, 3],
[4, 5, 6]])

print(transpose_array(a))

[[1 4]
 [2 5]
 [3 6]]


In [21]:
#Given a 1D array, determine and print the elements of the input arrays concatenated in the order they appear in the list.

def simple_array_concatentate(a):
    a=np.concatenate(a)
    return a

#Example 

sample_arr_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

print(simple_array_concatentate(sample_arr_list))


[1 2 3 4 5 6 7 8 9]


In [22]:
#Given a list of 2D arrays,  determine and print the arrays in the list concatenated vertically (i.e., one below the other).

def array_vertical_concatenate(a):
    a=np.concatenate(a,axis=0)
    return a

#Example
sample_arr_list = [np.array([[1, 2, 3], [4, 5, 6]]), np.array([[7, 8, 9], [10, 11, 12]])]

print(simple_array_concatentate(sample_arr_list))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# Write a function that takes in a two-dimensional NumPy array arr and an integer index, and removes the row at the given index from the array. 
# Your function should return the modified array.

def delete_rows(arr,index):
    return np.delete(arr,index,axis=0)

#Example
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(delete_rows(a,1))
    
    

[[10 20 30]
 [70 80 90]]


In [24]:
# Given a list of lists, where each inner list contains integers. 
# Using numpy.append() function add the sum of all integers in each inner list to the end of the list. Print the modified list of lists.

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

modified_list=[]
for inner_list in lst:
    sum_lst=sum(inner_list)
    modified_list.append(np.append(inner_list,sum_lst))

print(modified_list)


[array([1, 2, 3, 6]), array([ 4,  5,  6, 15]), array([ 7,  8,  9, 24])]


In [25]:
#Write a function that takes in a list of integers and a value n, and returns a new list containing the original list repeated n times. For example:
# repeat_list([1, 2, 3], 4) should print [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

def repeat_list(lst,n):
    return [np.array(lst).copy() for _ in range(n)]
print(repeat_list([1,2,3],4))

[array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3])]


In [26]:
# Given a list of lists, where each inner list contains integers. 
# Write a code using the numpy.resize() function to pad each inner list with zeros until it has length n.  For example:
# pad_lists([[1, 2, 3], [4, 5, 6,99], [7, 8]], 5)  #Print [array([1, 2, 3, 0, 0]), array([ 4,  5,  6, 99,  0]), array([7, 8, 0, 0, 0])]

lst = [[1, 2, 3], [4, 5, 6,99], [7, 8]]
pad = 5

padded_lst=[]

for inner_lst in lst:
    arr=np.array(inner_lst)
    arr.resize(pad)
    padded_lst.append(arr)
print(padded_lst)


[array([1, 2, 3, 0, 0]), array([ 4,  5,  6, 99,  0]), array([7, 8, 0, 0, 0])]


In [27]:
# Given a list of lists, where each inner list contains integers. 
# Write the code to find the unique values in each inner list, and then print a new list of lists containing the unique values.
# The inner lists in the returned list should be sorted in ascending order.

lst = [[3, 5, 2, 5], [2, 1, 4, 5], [5, 5, 3, 2]]

unique_lst=[]

for inner_lst in lst:
    unique_inner_lst=np.sort(np.unique(inner_lst))
    unique_lst.append(unique_inner_lst)

print(unique_lst)

[array([2, 3, 5]), array([1, 2, 4, 5]), array([2, 3, 5])]


In [31]:
#Write a function that takes in two lists of integers, a and b, and returns a Boolean value indicating whether all elements of a are also present in b.
#For example:
#print(all_values_in_list([1, 2, 3], [1, 2, 3, 4, 5])) #True
#print(all_values_in_list([1, 2, 3], [1, 2, 4, 5]))  #False

def comparison(a,b):
    a=np.array(a)
    b=np.array(b)
    return np.isin(a,b).all()
print(comparison([1, 2, 3], [1, 2, 3, 4, 5]))

True


In [2]:
#Given a 1D array, write the code to remove all leading and trailing zeros from the array. Print the trimmed array.

import numpy as np

arr = np.array([0, 0, 3, 4, 5, 0, 0, 0])

 
print(np.trim_zeros(arr))


[3 4 5]


In [3]:
#Given a dictionary, where the keys are tuples and the values are integers. Convert the dictionary into a NumPy array and print the result

import numpy as np

arr = np.array([[[1], [2]], [[3], [4]]])
print("Original shape:", arr.shape)  # (2, 2, 1)

squeezed = np.squeeze(arr)
print("New shape:", squeezed.shape)  # (2, 2)

print(squeezed)


Original shape: (2, 2, 1)
New shape: (2, 2)
[[1 2]
 [3 4]]


In [6]:
#Given two 1D numpy arrays, write the code to stack them horizontally (i.e., column-wise) to form a two-dimensional array.

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack as columns (along axis 1 → columns grow)
result = np.column_stack((a, b))
print(result)


[[1 4]
 [2 5]
 [3 6]]


In [7]:
#Given a 1D array, write your code to split the array in two equal sized array and print the result.

arr = np.array([1, 2, 3, 4, 5,6])
split = 2

print(np.split(arr,split))

[array([1, 2, 3]), array([4, 5, 6])]


Logic Operations


In [12]:
#Given an array arr, reshape the array in a 3D matrix. Create and print a new 2D boolean array "result" such that each element
# in "result" is True if all the elements in the corresponding 3D slice of "arr" are greater than a given scalar value "value", 
# and False otherwise.

arr = np.arange(27).reshape(3,3,3)
value=5
print(arr)
result=np.all(arr>value,axis=-1)
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
#Given an array arr, reshape the array in (2,3) matrix and determine and print whether any elements in each column of arr are greater than 5.

arr = np.arange(start = 1, stop = 7).reshape(2,3)
value=5
result=np.any(arr>value,axis=0)
print(result)

[False False  True]


In [14]:
#Given a 2D numpy array "arr", create and 
# print a new array "result" such that each element in "result" is the number of non-NaN elements in the corresponding row of "arr".

arr = np.array([[1, 2, np.nan], [4, np.nan, 6], [np.nan, 8, np.nan]])

result=np.sum(~np.isnan(arr),axis=1)
print(result)

[2 2 1]


In [15]:
#Given a 2D numpy array "arr", create and print a new array "result" such that each element in "result" is the mean of the non-NaN elements in the corresponding column of "arr".

arr = np.array([[1, 2, np.nan], [4, np.nan, 6], [np.nan, 8, np.nan]])

result = np.nanmean(arr, axis=0)
print(result)

[2.5 5.  6. ]


In [16]:
#Given two NumPy arrays a and b, determine and print whether all elements in a are equal to the corresponding elements in b.
a = [[1,2,3],
      [4,5,6]]

b = [[3,2,1],
      [6,5,4]]

result=np.equal(a,b)
print(result)

[[False  True False]
 [False  True False]]


In [19]:
#Given two 2D numpy arrays "arr1" and "arr2", create and print a new 2D array "result" such that each element in "result" is 1
# if the corresponding element in "arr1" is equal to the corresponding element in "arr2" and 0 otherwise.

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])

result=np.equal(arr1,arr2).astype(int)

print(result)

[[0 1 1]
 [1 1 1]
 [1 1 1]]


Random Sampling 

In [20]:
#Given a random seed set to 20, generate random 30 1-dimensional integer values

np.random.seed(20)
result=np.random.randn(30)
print(result)

[ 0.88389311  0.19586502  0.35753652 -2.34326191 -1.08483259  0.55969629
  0.93946935 -0.97848104  0.50309684  0.40641447  0.32346101 -0.49341088
 -0.79201679 -0.84236793 -1.27950266  0.24571517 -0.0441948   1.56763255
  1.05110868  0.40636843 -0.1686461  -3.18970279  1.12013226  1.33277821
 -0.24333877 -0.13003071 -0.10901737  1.55618644  0.12877835 -2.06694872]


In [21]:
#Given a random seed set to 20, generate random 30 2-dimensional integer values of size 5,5
np.random.seed(20)
result=np.random.rand(5,5)
print(result)


[[0.5881308  0.89771373 0.89153073 0.81583748 0.03588959]
 [0.69175758 0.37868094 0.51851095 0.65795147 0.19385022]
 [0.2723164  0.71860593 0.78300361 0.85032764 0.77524489]
 [0.03666431 0.11669374 0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686 0.17878052 0.77025193]]


In [24]:
#Given a random seed set to 10, generate random 2-dimensional random integer values of size 2,4 of a normal distribution where mean is 3 and standard deviation 2.5

np.random.seed(10)
mu=3
sigma=2.5
print(np.random.normal(size=(2,4)))

[[ 1.3315865   0.71527897 -1.54540029 -0.00838385]
 [ 0.62133597 -0.72008556  0.26551159  0.10854853]]


In [25]:
#Using the numpy.random module, generate a random sample of size 3 from the given distribution p, with a seed value of 20, for the array arr.

seed = 20
arr = [0,1, 2, 3, 4]
p = [0.1, 0, 0.3, 0.6, 0]

np.random.seed(seed)
result=np.random.choice(arr,3,p)
print(result)

[3 2 4]


In [27]:
#Given a random seed to 10, write a program that generates a random sample of size 10 from an exponential distribution with a scale of 2

np.random.seed(10)
result=np.random.exponential(scale=2,size=10)
print(result)

[2.95086889 0.04194059 2.0083226  2.7630426  1.38033131 0.50925978
 0.44145012 2.85866021 0.37051774 0.18497592]


In [29]:
# Create a function that generates a 2-dimensional array of shape (5,5) with random numbers drawn from an exponential distribution with a scale of 2. The function should take one parameter, a seed value, and use it to initialize the numpy random number generator. 
# The function should also return the mean and standard deviation of the elements in the generated array.

def generate_exponential_array(seed):
    np.random.seed(seed)
    arr=np.random.exponential(scale=2,size=(5,5))
    mean=np.mean(arr)
    std=np.std(arr)
    return mean,arr,std

arr, mean, std = generate_exponential_array(42)

print(arr)
print(mean)
print(std)

1.659699166617758
[[0.93853618 6.02024286 2.63349139 1.82588511 0.33924974]
 [0.33919258 0.11967754 4.02246173 1.83816431 2.46250012]
 [0.04159862 7.00711495 3.57285909 0.47737525 0.40135798]
 [0.40522285 0.72550746 1.48785566 1.13107413 0.68844599]
 [1.89274175 0.30046906 0.69103102 0.91255444 1.21786938]]
1.763804820988668


In [30]:
#Given a random seed to 10, 
# write a program that generates a triangular random 10 sample with a lower bound of 0, an upper bound of 1, and a mode of 0.5.

np.random.seed(10)
p=np.random.triangular(0,0.5,1,10)
print(p)

[0.66185849 0.10186253 0.57200948 0.64560184 0.49925295 0.33525859
 0.3146926  0.65397306 0.29078414 0.21016638]


Input and Output

In [2]:
#Given a data.npz file that contains multiple arrays, write a function to extract and return a specific array from the file by its name, 
# and then perform some calculations on that array, such as finding the mean and standard deviation. 
# Additionally, the program should handle cases where the specified array name does not exist in the file and raise an error message saying "Array {array_name} not found in {file_name}."

import numpy as np

#Create some arrays

np.random.seed(20)
array1=np.random.rand(3,3)
array2=np.random.rand(5,5)
array3=np.random.rand(7,7)

#Save the arrays in an npz.file

np.savez('data1.npz',array1=array1,array2=array2,array3=array3)

def extract_array(file_name,array_name):
    #Load the .npz file
    data=np.load(file_name)
    
    #Extract the array by its name
    try:
        array=data[array_name]
    except KeyError:
        raise ValueError(f"Array {array_name} not found in {file_name}")
    
    #Perform calculations on this array
    mean=np.mean(array)
    std=np.std(array)
    return mean,std,array

arr,mean,std=extract_array('data1.npz','array2')

print(arr)
print(mean)
print(std)



0.5159425588519038
0.2798807130486527
[[0.19385022 0.2723164  0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374 0.7512807  0.23921822]
 [0.25480601 0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792 0.4610394 ]
 [0.49794007 0.67941112 0.65078591 0.26879524 0.06732467]]


In [3]:
#Given a file array.npy, Use np.load to read a NumPy array from the file "array.npy" and use the resulting array to create a new array that is the element-wise square of the original array

import numpy as np

#Create some arrays

np.random.seed(10)
array1=np.random.uniform(1,2,(3,3)) #Create random array
np.save('array.npy',array1) #Save the arrays in an npy file

#Load original array 

original_array=np.load('array.npy')

#Output array

squared_array=original_array**2

print(squared_array)


[[3.13757682 1.04193454 2.66880656]
 [3.05831502 2.24552327 1.50012682]
 [1.43535463 3.09946839 1.36682015]]


In [4]:
#Given an array arr, save the file in csv format with the delimeter  as , (comma) 
# and load the same csv file and use boolean indexing to select elements that are greater than 10

import numpy as np

#Create some arrays
arr=np.arange(1,50,5)

np.savetxt('test.csv',arr,delimiter=',')

arr=np.loadtxt('test.csv',delimiter=',')

selected=arr[arr>10]

print(selected)




[11. 16. 21. 26. 31. 36. 41. 46.]


In [2]:
#Write a function that takes in a file path and a delimiter as input and returns the number of rows and columns in the file using the numpy.loadtxt 
# function. The function should handle the following edge cases:
#If the file is not found, the function should raise a FileNotFoundError with a message "File not found at specified path."
#If the delimiter is not found in the file, the function should raise a ValueError with a message "Delimiter not found in file."
#If the file is empty, the function should return (0,0)
#You should not use any other method or library apart from numpy.loadtxt.

import numpy as np

def get_file_dimensions(file_path, delimiter):
    try:
        data=np.loadtxt(file_path,delimiter=delimiter)
    except OSError:
        raise FileNotFoundError('File not found at specified path')
    except ValueError:
        raise ValueError('Delimiter not found in file')
    if data.size==0:
        return (0,0)
    else:
        return data.shape

In [7]:
#Write a function that takes a 2D NumPy array as input and returns a string representation of the array in the following format:
# [ [1 2 3] [4 5 6] ]
import numpy as np

def array_to_string(arr):
    arr_str=np.array_str(arr)

    # Format the string to desired output
    
    arr_str = arr_str.replace('[[', '[\n [')   # add newline after outer [
    arr_str = arr_str.replace(']]', ']\n]')   # add newline before closing ]
    
    return arr_str

# Test the function
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_to_string(arr))

[
 [1 2 3]
 [4 5 6]
]


In [14]:
#Write a function that takes a 3D NumPy array as input and returns a string representation of the array in the following format:

#[ 
# [ 1 2] 
# [ 3 4] 
#] 
#[ 
# [ 5 6] 
# [ 7 8] 
#]

import numpy as np
 
def array_to_string(arr):
    # Initialize an empty list to store the string representation of each layer
    layers = []
 
    # Iterate over the layers of the array
    for layer in arr:
        # Use numpy.array_str to generate a string representation of the layer
        layer_str = np.array_str(layer)
 
        # Replace '[[' with '[\n [' and ']]' with ']\n]'
        layer_str = layer_str.replace('[[', '[\n [')
        layer_str = layer_str.replace(']]', ']\n]')
 
        # Replace '[' with '[' and ']' with ']'
        layer_str = layer_str.replace('[', '[ ')
        layer_str = layer_str.replace(']', '] ')
 
        # Replace '  ' with ' '
        layer_str = layer_str.replace('  ', ' ')
 
        # Add the string representation of the layer to the list
        layers.append(layer_str)
 
    # Join the layers with a newline character
    array_str = '\n'.join(layers)
 
    return array_str
 
# Test the function
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_to_string(arr))

[ 
 [ 1 2] 
 [ 3 4] 
] 
[ 
 [ 5 6] 
 [ 7 8] 
] 


Sorting, searching and counting

In [1]:
#Given a numpy array 'arr', sort and print 'arr' by score field.

import numpy as np

arr = np.array([('Alice', 92), ('Bob', 88), ('Charlie', 95), ('Dan', 90)],
                dtype=[('name', 'U10'), ('score', 'i4')])


arr.sort(order='score')
print(arr)

[('Bob', 88) ('Dan', 90) ('Alice', 92) ('Charlie', 95)]


In [2]:
#Given a 2D array, sort the array by column wise and print the results

arr=np.array([[900,3,1],[100,1,29]])

sarr=np.sort(arr,axis=0)
print(sarr)

[[100   1   1]
 [900   3  29]]


In [4]:
#Given a 2D numpy array of shape (m, n) where m is the number of rows and n is the number of columns, write a function that sorts each row of the array in ascending order, and then returns the indices of the original position of the elements in each row after sorting.
# Your function should not use any loops and should only use numpy functions such as sort and argsort.

import numpy as np

arr=np.array([[4,2,3],[1,6,5],[9,7,8]])

def sort_and_return(arr):
    indices=np.argsort(arr,axis=1)
    sorted_arr=np.sort(arr)
    return indices,sorted_arr

indices,sorted_arr=sort_and_return(arr)
print(indices)
print(sorted_arr)



[[1 2 0]
 [0 2 1]
 [1 2 0]]
[[2 3 4]
 [1 5 6]
 [7 8 9]]


In [6]:
#Given a 2D numpy array of shape (m, n) where m is the number of rows and n is the number of columns, write a function that sorts each column of the array in descending order and returns a new 2D array that contains only the top k elements from each column.
#Your function should not use any loops and should only use numpy functions such as sort and argsort.

import numpy as np

arr=np.array([[1,2,3],[1,6,5],[9,7,8]])

def sort_and_return_top_k(arr,k):
    s_arr=-np.sort(-arr,axis=0)
    return s_arr[:k,:]

top_k_arr=sort_and_return_top_k(arr,2)
print(top_k_arr)
    

[[9 7 8]
 [1 6 5]]
